version: '3.4'

x-cache-from:
  - &api-cache-from
    cache_from:
      - ${NGINX_IMAGE:-vitaliybratyshov/hack-backend:latest}
      - ${PHP_IMAGE:-vitaliybratyshov/hack-nginx:latest}

services:
  php:
    build:
      context: .
      target: api_platform_php
      <<: *api-cache-from
    image: vitaliybratyshov/hack-backend:latest
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    depends_on:
      - db
      - similar
    volumes:
      - ./:/srv/api:rw,cached
      - ./docker/php/conf.d/api-platform.dev.ini:/usr/local/etc/php/conf.d/api-platform.ini
      # if you develop on Linux, you may use a bind-mounted host directory instead
      # - ./api/var:/srv/api/var:rw
      - dev-certs:/certs:ro,nocopy

  api:
    build:
      context: .
      target: api_platform_nginx
      <<: *api-cache-from
    image: vitaliybratyshov/hack-nginx:latest
    depends_on:
      - php
    ports:
      - 8080:80
    volumes:
      - ./public:/srv/api/public:ro

  vulcain:
    image: dunglas/vulcain
    environment:
      - CERT_FILE=/certs/localhost.crt
      - KEY_FILE=/certs/localhost.key
      - UPSTREAM=http://api
    depends_on:
      - api
    volumes:
      - dev-certs:/certs:ro,nocopy
    ports:
      - target: 443
        published: 8443
        protocol: tcp

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD=!ChangeMe!
      - POSTGRES_USER=api-platform
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./api/docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - target: 5432
        published: 5432
        protocol: tcp

  mercure:
    image: dunglas/mercure
    environment:
      - ALLOW_ANONYMOUS=1
      - CERT_FILE=/certs/localhost.crt
      - CORS_ALLOWED_ORIGINS=*
      - DEMO=1
      - JWT_KEY=!ChangeMe!
      - KEY_FILE=/certs/localhost.key
      - PUBLISH_ALLOWED_ORIGINS=https://localhost:1337 # required for publishing from the demo page
    volumes:
      - dev-certs:/certs:ro,nocopy
    ports:
      - target: 443
        published: 1337
        protocol: tcp

  similar:
    image: vitaliybratyshov/hack-simular:latest
    environment:
      - PGSQL_DSN=host=db user=api-platform password=!ChangeMe! dbname=api port=5432 sslmode=disable
    depends_on:
      - db
    ports:
      - 8081:8081
    restart: always


networks:
  esnet:

volumes:
  db-data: {}
  dev-certs: {}
  esdata1:
    driver: local